# in _config.yml
title: "Deep Learning for Brain-Signal Decoding from Electroencephalography (EEG)"
logo: images/braindecode-logo.svg
execute:
  execute_notebooks: "off"
html:
  comments:
    hypothesis: true
    utterances:
      repo: "robintibor/eeg-deep-learning-phd-thesis"
bibtex_bibfiles:
    - references.bib
sphinx:
  extra_extensions:
   - sphinx_subfigure
