# in _config.yml
title: "Deep Learning for Brain-Signal Decoding from Electroencephalography (EEG)"
logo: images/braindecode-logo.svg
execute:
  execute_notebooks: "off"
html:
  comments:
    hypothesis: true
    utterances:
      repo: "robintibor/eeg-deep-learning-phd-thesis"
bibtex_bibfiles:
    - references.bib
bibtex_reference_style: author_year
sphinx:
  extra_extensions:
   - sphinx_subfigure
  config:
    bibtex_reference_style: author_year 
    exclude_patterns:
     - not-included-yet
     - not-to-be-included
     - _build
     - docs
     - images
    html_context:
      default_mode: "light"
    html_theme_options:
      navbar_end:
        - "navbar-icon-links"
