#!/usr/bin/env python
# coding: utf-8

# (introduction)=
# # Introduction

# ```{admonition} Deep Learning (DL) is a very promising method to decode brain signals from EEG
# * Deep learning may extract more information from EEG signals that humans can
# * Deep learning may improve EEG-based diagnosis, enable new assistive technologies and advance scientific understanding of the EEG signal
# * Our EEG decoding deep learning models perform as good or better than feature-based methods
# ```

# Machine learning (ML), i.e., using data to learn programs that can solve specific tasks, has the potential to benefit medical applications. Compared to humans, machine-learning programs can process larger amounts of data and may extract different information. For example, machine-learning algorithms have processed the large amounts of signals recorded in an intensive-care unit to predict kidney failure {cite:p}`rank2020deep,tomavsev2019clinically`, diagnosed breast cancer using high-frequency features usually ignored by doctors {cite:p}`makino2022differences`, translated brain signals into control signals for external devices in real-time {cite:p}`abiri2019comprehensive` and detected pathology from long brain signal recordings {cite:p}`gemein2020machine,schirrmeisterdeeppathology`. Used in this way, machine learning may improve medical interventions, enable new assistive devices and advance scientific understanding.

# Brain-signal decoding is an especially interesting problem to tackle with machine learning. Brain signals contain a lot of information, yet are hard to interpret for humans. Additionally, more brain signals can be recorded than humans could possibly process. Machine-learning algorithms can help doctors triage patients by quickly detecting stroke biomarkers from computed tomography (CT) {cite:p}`chavva2022deep` and enable brain-computer interfaces by recognizing people's intentions from electroencephalographic (EEG) in real time  {cite:p}`abiri2019comprehensive`. Also, as brain signals are far from being fully understood, machine-learning algorithms have the potential to advance scientific understanding by finding new brain-signal biomarkers for different pathologies {cite:p}`raghu2020survey`.
# 

# Electroencephalographic (EEG) brain-signal recordings are well-suited for machine learning due to the ease of acquiring them and the difficulty of interpreting them manually. Large EEG datasets can be created relatively easy compared to other medical recordings as EEG recordings are fairly cheap and lack substantial side effects.  Furthermore, EEG recordings are particularly challenging for humans to interpret, making them a promising target for information extraction through machine learning. Some clinical applications of EEG such as pathology diagnosis may be improved by machine learning, while others such as brain-computer interfaces are even only possible because of machine learning. Finally, since the information contained in the EEG signal is far from being fully understood, machine learning may even help understand the EEG signal itself better.

# Deep learning is a very promising approach for brain-signal decoding from EEG. The term deep learning describes machine-learning models with multiple computational stages, where the computational stages are typically trained jointly to solve a given task {cite:p}`lecun_deep_2015,schmidhuber_deep_2015`. Convolutional neural networks (ConvNets) are deep learning models that are  inspired by computational structures in the visual cortex of the brain and have in recent times become very successful models for a wide variety of tasks, including object detection in images, speech recognition from audio or machine translation.  ConvNets only have very general assumptions about the properties of their training signals embedded into them (such as smoothness and hierarchical structure) and have shown great success on a variety of natural signals. Therefore, ConvNets are very promising to apply to hard-to-understand natural signals like EEG signals.

# Prior to the work presented in this thesis, it was unclear how well ConvNet architectures can decode EEG signals compared to hand-engineered, feature-based approaches. The high dimensionality, low signal-to-noise ratio and large signal variability (e.g., from person to person or even session to session for the same person) of EEG data present challenges that may  be better addressed by feature-based approaches that exploit more specific assumptions about the EEG signal. While there have been previous efforts to apply deep learning to EEG, a systematic study of the performance of modern ConvNets on EEG decoding compared with a strong feature-based baseline and including the impact of network architecture and training hyperparameters, was lacking. Furthermore, research into understanding what features the ConvNets extract from the EEG signal had been limited.

# We therefore created several ConvNet architectures to thoroughly evaluate on EEG decoding. We first evaluated our ConvNet's decoding performance under a range of different hyperparameter choices on  widely studied movement-related decoding tasks and found they perform at least as good as a strong feature-based baseline. The ConvNets also generalized well to a range of other decoding tasks, including other task-related decoding tasks as well as pathology diagnosis. We also developed visualizations to understand the features the ConvNets extract from the EEG signal, finding that their predictions are sensitive to plausible neurophysiological features.

# In this thesis, I will first describe the research on deep learning EEG decoding prior to our work, then proceed to describe the deep network architectures and training methods we developed to rival or surpass feature-based EEG decoding approaches on movement- and other task-related EEG decoding tasks as well as pathology diagnosis. Furthermore, I also describe the visualization methods we developed that suggest the networks are using plausible neurophysiological patterns to solve their tasks.
